{
    Assert_AreEqual: "参数{0}值应为{1}，实际值为{2}",
    Assert_AreNotEqual: "参数{0}值不应为{1}，实际值为{2}",
    Assert_AreSame: "参数{0}应为{1}，实际为{2}",
    Assert_AreNotSame: "参数{0}不应为{1}，实际为{2}",
    Assert_IsTrue: "参数{0}的条件判断应为真",
    Assert_IsFalse: "参数{0}的条件判断应为假",
    Assert_IsInstanceOfType: "参数{0}的类型应为{1}，实际为{2}",
    Assert_IsNotInstanceOfType: "参数{0}的类型不应为{1}，实际为{2}",
    Assert_IsNull: "参数{0}应为空，实际不为空",
    Assert_IsNotNull: "参数{0}不应为空，实际为空",
    Assert_IsStringNullOrEmpty: "参数{0}字符串应为空，实际不为空",
    Assert_IsStringNotNullOrEmpty: "参数{0}字符串不应为空，实际为空",
    Assert_IsInRange: "参数{0}的值为{1}，应该大于等于{2}，小于等于{3}",
    Assert_IsNotInRange: "参数{0}的值为{1}，应该小于等于{2}，大于等于{3}",
    Assert_EnumValueIsDefined: "参数{0}的值为{2}，应为枚举类型{1}的值之一",
    Assert_TypeIsAssignableFromType: "参数{0}的类型为{2}，应为类型{1}或其子类型",

    SaveSuccessfully: "保存成功",
    SaveFailure: "保存失败",
    DeleteSuccessfully: "删除成功",
    DeleteFailure: "删除失败",

    FileNotFound: "文件不存在",

    DataStatus_Normal: "正常",
    DataStatus_ReadOnly: "只读",
    DataStatus_Locked: "锁定",
    DataStatus_Deleted: "删除",

    Data_Requried: "{0}是必需的",
    Data_DataType: "{0}的数据类型不对",
    Data_EqualsTo: "{0}必须与{1}一致",
    Data_FloatRange: "{0}的输入范围是从{1}至{2}的",
    Data_IntegerRange: "{0}的输入范围是从{1}至{2}的",
    Data_Regex: "{0}的输入格式不符合要求",
    Data_StringLength: "{0}最多只能输入{1}个字符",
    Data_StringLengthRange: "{0}只能输入{1}至{2}个字符",
    Data_IdCard: "身份证格式不对",
    Data_Email: "邮箱格式不对",
    Data_Phone: "电话格式不对"
}