{
    CurrentSelectedClient: "当前站点：",
    ClearSelectedClient: "清除",
    NoClientSelected: "未选择站点",

    RequireAuthentication: "请先登录",
    WelcomeUser: "欢迎{0}",
    SignOn: "登录",
    SignOff: "退出",
    Register: "注册新用户",
    ResetPassword: "重置密码",
    ResetPasswordTitle: "重置密码通知",
    RefreshCaptcha: "看不清楚？",
    CaptchaNotCorrect: " 验证码不正确",
    SignOnFailed: "登录失败。",
    RegisterFailed: "注册失败。",
    AccountNotFound: "用户不存在",
    AccountLocked: "该用户已经被锁定",
    AccountIsReadOnly: "该用户只能查看内容",
    ClientNotFound: "客户端不存在",
    ClientSessionNotFound: "该客户端会话不存在",
    UserSessionExpired: "用户会话已失效",
    UserSessionNotFound: "用户会话不存在",
    ChangePassword: "修改你的登录密码",
    PasswordInvalid: "密码至少要6位",
    ConfirmPasswordIsNotSameToPassword: "确认密码必须与密码一致",
    ChangePasswordSuccessfully: "密码修改成功，请使用新密码。",
    ResetPasswordSuccessfully: "密码重置成功，请注意查收Email或手机短信，使用新密码。",
    ForgetPassword: "忘记密码",
    RememberMe: "记住我的帐号信息",
    Captcha: "验证码",
    EmailOrMobileNotFound: "未查到相应的Emial或者电话",

    DuplicatedAccount: "帐户已存在",
    DuplicatedEmail: "Email已存在",
    DuplicatedMobile: "手机已存在",
    DuplicatedPhone: "电话已存在",

    SignOnInfo_AccountOrEmailOrMobile: "用户名",
    SignOnInfo_Account: "用户名",
    SignOnInfo_Password: "密码",

    RegisterInfo_Account: "用户",
    RegisterInfo_Email: "Email",
    RegisterInfo_Password: "密码",
    RegisterInfo_ConfirmPassword: "确认密码",

    ResetPasswordInfo_EmailOrMobile: "输入Email或手机：",

    ChangePasswordInfo_OldPassword: "原密码",
    ChangePasswordInfo_NewPassword: "新密码",
    ChangePasswordInfo_ConfirmPassword: "确认新密码",

    PermissionType_Operation: "操作权限",
    PermissionType_DataField: "字段权限",
    PermissionType_DataScope: "行权限",

    User_UserId: "用户ID",
    User_Account: "用户",
    User_Password: "密码",
    User_ClientId: "客户端",
    User_SecurityCode: "安全码",
    User_NickName: "昵称",
    User_FullName: "姓名",
    User_Sex: "性别",
    User_Email: "Email",
    User_Mobile: "手机",
    User_Locale: "语言",
    User_TimeZone: "时区",
    User_Theme: "主题",
    User_Skin: "皮肤",
    User_Avatar: "头像",
    User_Status: "状态",
    User_UserRoles: "角色",

    Role_RoleName: "角色",
    Role_ActiveTime: "激活日期",
    Role_ExpiryTime: "失效日期",
    Role_Status: "状态",

    Permission_GroupName: "分组",
    Permission_PermissionName: "名称",
    Permission_PermissionType: "权限类型",
    Permission_Position: "位置",
    Permission_Uri: "资源地址"
}