{
    DefaultTheme: "Default",
    DefaultSkin: "Default",
    DefaultLocale: "zh-CN",
    DefaultTimeZone: "8.0",
    SiteLogo: "/favicon.ico",
    SiteName: "网站名称",
    DefaultTitle: "网站标题",
    DefaultMetaKeywords: "网站MetaKeywords",
    DefaultMetaDescription: "网站MetaDescription",

    Home: "首页",
    About: "关于",

    Info: "提示",
    Warning: "警告",
    Error: "错误",
    OK: "确定",
    Cancel: "取消",
    Close: "关闭",

    New: "新增",
    Add: "新增",
    Insert: "新增",
    Edit: "编辑",
    Delete: "删除",
    Save: "保存",
    DeleteWarning: "确认要删除记录？",
    SaveSuccessfully: "保存成功",
    SaveFailure: "保存失败",

    Search: "搜索",

    FirstPage: "首页",
    PrevPage: "上一页",
    NextPage: "下一页",
    LastPage: "末页",
    TotalPages: "共{0}页",
    TotalRecords: "共{0}条",
    PageInfo: "当前第{0}页，共{1}页",
    RecordInfo: "当前第{0}条，共{1}条记录",
    GotoPage: "转到",
    GO: "GO",

    MenuItem_Name: "名称",
    MenuItem_Caption: "标题",
    MenuItem_LinkUrl: "链接地址",
    MenuItem_ProtectedUri: "权限地址",
    MenuItem_Target: "链接目标"
}