{
    Content_Index_Title: "内容管理",
    Content_Index_Description: "网站的内容管理",
    Content_Add_Title: "新增内容",
    Content_Add_Description: "新增网站内容",
    AppSettings_Index_Title: "参数设置",
    AppSettings_Index_Description: "常用的参数设置",
    AppSettings_App_Title: "参数设置",
    AppSettings_App_Description: "常用的参数设置",
    BasicData_Index_Title: "基础数据管理",
    BasicData_Index_Description: "管理系统中的所有基础数据，基础数据按类别划分",
    Category_Index_Title: "分类管理",
    Category_Index_Description: "常用的分类管理，分类可用于区分网站栏目、功能分区等",
    Category_Cate_Title: "分类管理",
    Category_Cate_Description: "常用的分类管理，分类可用于区分网站栏目、功能分区等",
    Menu_Index_Title: "菜单管理",
    Menu_Index_Description: "管理除系统管理外的所有菜单项，各菜单按菜单组分开，如主菜单、页头菜单、页脚菜单等",
    UserGroup_Index_Title: "用户分组",
    UserGroup_Index_Description: "管理用户分组，设置分组的用户，用户分组相当于部门、科室、项目组等，可对应于其他系统的非角色划分组织",


    Content_ContentId:"内容Id",
    Content_Language:"语言",
    Content_Title:"标题",
    Content_Keywords:"关键字",
    Content_Description:"描述",
    Content_ImageUrl:"图片地址",
    Content_LinkUrl:"链接地址",
    Content_ShortUrl:"友好地址",
    Content_PlainBody:"文本内容",
    Content_HtmlBody:"Html内容",
    Content_ContentType:"内容类型",
    Content_Properties:"内容属性",
    Content_ContentSize:"内容大小",
    Content_Published:"已发布",
    Content_ReadCount:"查看次数",
    Content_CreatorId:"创建人Id",
    Content_CreatorName:"创建人",
    Content_CreateTime:"创建时间",
    Content_ModifierId:"修改人Id",
    Content_ModifierName:"修改人",
    Content_ModifiedTime:"修改时间",
    Content_PublisherId:"发布人Id",
    Content_PublisherName:"发布人",
    Content_PublishTime:"发布时间",
    Content_ShowOrder:"显示顺序",

    ContentType_Text: "普通文本",
    ContentType_Html: "Html文本",
    ContentType_Link: "链接",
    ContentType_Image: "图像",
    ContentType_File: "下载文件",
    ContentType_Audio: "音频",
    ContentType_Video: "视频",
    ContentType_Org: "单位机构",
    ContentType_Person: "人员",
    ContentType_Contact: "联系方式",

    AppSetting_SiteName: "网站名称",
    AppSetting_AppName: "应用名称",
    AppSetting_Category: "配置分类",
    AppSetting_Name: "配置名称",
    AppSetting_Caption: "显示标题",
    AppSetting_Value: "配置值",
    AppSetting_ShowOrder: "显示顺序",

    BasicDataItem_SiteName: "网站名称",
    BasicDataItem_AppName: "应用名称",
    BasicDataItem_AppName: "应用名称",
    BasicDataItem_Category: "分类",
    BasicDataItem_Name: "名称",
    BasicDataItem_Caption: "显示标题",
    BasicDataItem_Value: "值",
    BasicDataItem_GroupName: "分组",
    BasicDataItem_ShowOrder: "显示顺序",
    BasicDataItem_IsValid: "有效",
    BasicDataItem_ParentName: "父级名称",

    Category_SiteName: "网站名称",
    Category_Language: "语言",
    Category_Code: "分类编码",
    Category_Name: "分类名称",
    Category_GroupName: "分组",
    Category_ShowOrder: "显示顺序",
    Category_Status: "状态",
    Category_ParentCode: "父级名称",
    CategoryUserGroup_SiteName: "网站名称",
    CategoryUserGroup_Language: "语言",
    CategoryUserGroup_CategoryCode: "分类编码",
    CategoryUserGroup_UserGroupName: "用户分组",

    UserGroup_SiteName: "网站名称",
    UserGroup_Name: "分组名称",
    UserGroup_Caption: "显示标题",
    UserGroup_ShowOrder: "显示顺序",
    UserGroup_ParentName: "父级分组",
    UserGroupUser_SiteName: "网站名称",
    UserGroupUser_UserGroupName: "分组名称",
    UserGroupUser_UserId: "用户",

    WebSite_SiteName: "网站名称",
    WebSite_UrlStartWith: "网址",

    SubSite_SiteName: "网站名称",
    SubSite_SubSiteName: "子站点",
    SubSite_Language: "语言",
    SubSite_DateTimeFormat: "长时间格式",
    SubSite_DateFormat: "日期格式",
    SubSite_TimeFormat: "时间格式",
    SubSite_CurrencyFormat: "货币格式",
    SubSite_NumberFormat: "浮点格式",
    SubSite_TimeZone: "时区",
    SubSite_DefaultPageTitle: "默认页面标题",
    SubSite_DefaultMetaKeywords: "meta keywords",
    SubSite_DefaultMetaDescription: "meta description",

    SiteMenuItem_Name: "名称",
    SiteMenuItem_Caption: "标题",
    SiteMenuItem_LinkUrl: "链接地址",
    SiteMenuItem_ProtectedUri: "权限地址",
    SiteMenuItem_Target: "链接目标",
    
    PageTemplateControl_TemplateName: "页面模板",
    PageTemplateControl_Section: "页面区块",
    PageTemplateControl_ControlPath: "控件路径",
    PageTemplateControl_ControlParas: "控件参数",
    PageTemplateControl_Container: "容器",
    PageTemplateControl_ShowOrder: "排序",
    PageTemplateControl_Cached: "缓存",
    PageTemplateControl_CacheMunites: "缓存分钟",
    
    WebPageControl_Section: "页面区块",
    WebPageControl_ControlPath: "控件路径",
    WebPageControl_ControlParas: "控件参数",
    WebPageControl_Container: "容器",
    WebPageControl_ShowOrder: "排序",
    WebPageControl_Cached: "缓存",
    WebPageControl_CacheMunites: "缓存分钟"
}